openapi: 3.0.3
info:
  title: todo_list
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost'
paths:
  /api/task:
    get:
      summary: 任務列表
      operationId: ''
      description: ''
      parameters:
        -
          in: query
          name: sort_field
          description: '排序方式, 預設為"desc"排'
          example: asc
          required: true
          schema:
            type: string
            description: '排序方式, 預設為"desc"排'
            example: asc
        -
          in: query
          name: name
          description: '用"name"過濾任務, 預設為空'
          example: abc
          required: true
          schema:
            type: string
            description: '用"name"過濾任務, 預設為空'
            example: abc
        -
          in: query
          name: description
          description: '用"description"過濾任務, 預設為空'
          example: abc
          required: true
          schema:
            type: string
            description: '用"description"過濾任務, 預設為空'
            example: abc
        -
          in: query
          name: status
          description: '用"status"過濾任務, 預設為空'
          example: pending
          required: true
          schema:
            type: string
            description: '用"status"過濾任務, 預設為空'
            example: pending
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    \"success\": true,\n    \"msg\": \"ok\",\n    \"data\": [\n        \"data\": [\n            {\n                \"id\": 1,\n                \"name\": \"Task 1\",\n                \"description\": \"Task 1 description\",\n                \"created_at\": \"2021-09-01 00:00:00\",\n                \"updated_at\": \"2021-09-01 00:00:00\",\n                \"due_date\": \"2024-05-03\",\n                \"status\": \"pending\"\n            }\n        ]\n    ]\n}"
      tags:
        - 'Task Action 任務操作'
      security: []
    post:
      summary: 任務新增
      operationId: ''
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    \"success\": true,\n    \"msg\": \"Task \"{task_name}\" created successfully\"\n}"
      tags:
        - 'Task Action 任務操作'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 任務名稱
                  example: numquam
                description:
                  type: string
                  description: 任務描述
                  example: 'Velit totam iusto doloribus.'
                due_date:
                  type: string
                  description: 任務截止日期(Y/m/d)
                  example: '2025-09-01'
                status:
                  type: string
                  description: '任務狀態(pending, completed)'
                  example: pending
              required:
                - name
                - description
                - due_date
                - status
      security: []
  '/api/task/{id}':
    put:
      summary: 任務更新
      operationId: ''
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    \"success\": true,\n    \"msg\": \"Task \"{task_name}\" updated successfully\"\n}"
      tags:
        - 'Task Action 任務操作'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 任務名稱
                  example: rerum
                description:
                  type: string
                  description: 任務描述
                  example: 'Sit ut exercitationem rerum incidunt rerum velit ea.'
                due_date:
                  type: string
                  description: 任務截止日期(Y/m/d)
                  example: '2025-09-01'
                status:
                  type: string
                  description: '任務狀態(pending, completed)'
                  example: pending
              required:
                - name
                - description
                - due_date
                - status
      security: []
    delete:
      summary: 任務刪除
      operationId: ''
      description: ''
      parameters: []
      responses:
        200:
          description: ''
          content:
            text/plain:
              schema:
                type: string
                example: "{\n    \"success\": true,\n    \"msg\": \"Task \"{task_name}\" deleted successfully\"\n}"
      tags:
        - 'Task Action 任務操作'
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the task.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: 'Task Action 任務操作'
    description: "\n APIs for allocate vacation"
